package center

import (
	"net/http"
)

func serveConsole(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		methodNotAllowed(w, http.MethodGet, http.MethodHead)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("X-Frame-Options", "DENY")
	w.Header().Set("Content-Security-Policy", "default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'")
	if r.Method == http.MethodGet {
		_, _ = w.Write([]byte(consoleHTML))
	}
}

const consoleHTML = `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Remote Connect MCP</title>
  <style>
    :root{color-scheme:dark;--bg:#0f1724;--sidebar:#111b2b;--topbar:#142136;--panel:#18263a;--panel-alt:#1c2d44;--line:#2b3d55;--line-soft:#22334a;--text:#eef5ff;--muted:#93a6bd;--accent:#4ea9e8;--accent-strong:#287fbd;--ok:#4ed18a;--warn:#f2b85b;--bad:#f27777;--shadow:0 12px 30px rgba(0,0,0,.16)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}a{color:inherit;text-decoration:none}
    h1,h2,h3,p{margin:0}button,input,select,textarea{font:inherit}.hidden{display:none!important}.error{color:var(--bad)}.muted{color:var(--muted)}
    .admin-shell{min-height:100vh;display:flex}.sidebar{width:244px;flex:0 0 244px;background:var(--sidebar);border-right:1px solid var(--line);display:flex;flex-direction:column;position:sticky;top:0;height:100vh;z-index:5}.brand{height:72px;display:flex;align-items:center;gap:11px;padding:0 21px;border-bottom:1px solid var(--line)}.brand-mark{width:34px;height:34px;display:grid;place-items:center;border-radius:8px;background:linear-gradient(145deg,#338dc7,#1b567f);box-shadow:0 5px 14px rgba(18,117,178,.25);font-size:11px;font-weight:800;letter-spacing:.5px}.brand-name{font-weight:700;letter-spacing:.2px}.brand-sub{display:block;color:var(--muted);font-size:11px;margin-top:1px}.nav{padding:18px 12px;overflow:auto}.nav-group{margin-bottom:18px}.nav-group-title{padding:0 12px 8px;color:#7388a3;font-size:11px;font-weight:700;letter-spacing:.12em}.nav-link{display:flex;align-items:center;gap:11px;padding:10px 12px;border-radius:7px;color:#afbed0;margin:2px 0;transition:background .15s,color .15s}.nav-link:hover{background:#1b2c43;color:var(--text)}.nav-link.active{background:rgba(62,151,211,.2);color:#d9efff;box-shadow:inset 3px 0 0 var(--accent)}.nav-icon{width:18px;text-align:center;color:#7f9ab7;font-size:15px}.nav-link.active .nav-icon{color:var(--accent)}.sidebar-footer{margin-top:auto;border-top:1px solid var(--line);padding:14px 20px;color:var(--muted);font-size:12px;display:flex;align-items:center;gap:8px}.status-dot{width:7px;height:7px;border-radius:50%;background:var(--ok);box-shadow:0 0 0 3px rgba(78,209,138,.12)}
    .content{min-width:0;flex:1}.topbar{height:72px;display:flex;align-items:center;justify-content:space-between;gap:20px;padding:0 30px;background:rgba(20,33,54,.96);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:4}.breadcrumb{display:flex;align-items:baseline;gap:13px}.eyebrow{color:#7189a6;font-size:10px;font-weight:700;letter-spacing:.16em}.topbar h1{font-size:19px;letter-spacing:.2px}.top-actions{display:flex;align-items:center;gap:10px}.refresh-state{font-size:12px;white-space:nowrap}.workspace{max-width:1540px;margin:0 auto;padding:28px 30px 46px}.page-section{scroll-margin-top:92px;margin-bottom:24px}.section-head{display:flex;justify-content:space-between;align-items:flex-end;gap:15px;margin:0 2px 13px}.section-head h2{font-size:17px;letter-spacing:.1px}.section-head p{color:var(--muted);font-size:12px;margin-top:3px}.section-meta{color:#7088a4;font-size:11px;white-space:nowrap}
    .stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:13px;margin-bottom:14px}.stat{background:var(--panel);border:1px solid var(--line);border-radius:9px;padding:16px 18px;position:relative;overflow:hidden;box-shadow:var(--shadow)}.stat:after{content:"";position:absolute;width:64px;height:64px;border-radius:50%;right:-22px;bottom:-25px;background:rgba(78,169,232,.08)}.stat b{display:block;font-size:27px;line-height:1.1;font-weight:700}.stat span{display:block;color:var(--muted);font-size:12px;margin-top:8px}.stat .stat-label{display:flex;align-items:center;gap:6px}.stat .mini-dot{width:6px;height:6px;border-radius:50%;display:inline-block;background:var(--accent)}.stat:nth-child(2) .mini-dot{background:var(--ok)}.stat:nth-child(3) .mini-dot{background:var(--warn)}.stat:nth-child(4) .mini-dot{background:#b58cff}
    .panel{background:var(--panel);border:1px solid var(--line);border-radius:9px;overflow:hidden;box-shadow:var(--shadow)}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:14px 17px;border-bottom:1px solid var(--line)}.panel-head h3,.panel-head h2{font-size:14px;font-weight:650}.panel-head .muted{font-size:12px}.panel-body{padding:17px}.body{padding:17px}.stack{display:grid;gap:11px}.row{display:flex;gap:10px;align-items:center}.overview-grid{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(280px,.85fr);gap:14px}.quick-list{display:grid;gap:11px}.quick-item{display:flex;align-items:flex-start;gap:11px;padding:11px 12px;border:1px solid var(--line-soft);background:rgba(255,255,255,.018);border-radius:7px}.quick-icon{flex:0 0 28px;width:28px;height:28px;display:grid;place-items:center;border-radius:6px;background:#203b55;color:var(--accent);font-size:13px}.quick-item b{display:block;font-size:13px}.quick-item span{display:block;color:var(--muted);font-size:12px;margin-top:2px}.inline-link{color:var(--accent);font-size:12px}.inline-link:hover{text-decoration:underline}
    .form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.field{display:grid;gap:6px}.field.full{grid-column:1/-1}.field label{font-size:12px;color:var(--muted)}.field small{color:#738ba7;font-size:11px}input,select,textarea,button{color:inherit;background:#101c2c;border:1px solid var(--line);border-radius:6px;padding:9px 10px;outline:none}input,select,textarea{width:100%}input:focus,select:focus,textarea:focus{border-color:var(--accent);box-shadow:0 0 0 2px rgba(78,169,232,.12)}textarea{min-height:125px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px}button{cursor:pointer;background:#1b2b40;transition:background .15s,border-color .15s,transform .1s}button:hover{border-color:#5b7591;background:#233a55}button:active{transform:translateY(1px)}button.primary{background:var(--accent-strong);border-color:#3a9ad5;color:#f5fbff}button.primary:hover{background:#328ecb}button.danger{color:#ffabab}.button-row{display:flex;justify-content:flex-end;align-items:center;gap:9px;margin-top:2px}.icon-button{width:34px;height:34px;padding:0;display:grid;place-items:center;font-size:17px}.help-box{border:1px solid var(--line-soft);border-radius:7px;padding:13px 14px;background:rgba(255,255,255,.018);color:var(--muted);font-size:12px}.help-box strong{color:var(--text);font-weight:600;display:block;margin-bottom:5px}
    .table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:600px}th,td{text-align:left;padding:11px 13px;border-bottom:1px solid var(--line-soft);vertical-align:top;white-space:nowrap}td:first-child{white-space:normal}tr:last-child td{border-bottom:0}th{color:#8298b2;font-size:11px;font-weight:600;letter-spacing:.03em;background:rgba(10,18,30,.18)}tbody tr{cursor:pointer}tbody tr:hover{background:#1c3048}.pill{display:inline-flex;align-items:center;padding:2px 8px;border-radius:999px;border:1px solid var(--line);font-size:11px}.online{color:var(--ok)}.offline{color:var(--muted)}.failed,.canceled{color:var(--bad)}.running,.dispatching{color:var(--accent)}.queued,.cancel_requested{color:var(--warn)}
    pre{margin:0;min-height:220px;max-height:520px;overflow:auto;white-space:pre-wrap;word-break:break-word;background:#0a121e;padding:14px;border-radius:6px;border:1px solid var(--line-soft);font:12px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}.code-box{margin-top:11px}.section-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(310px,.65fr);gap:14px}.page-section:not(.active-section){display:none}.login{max-width:420px;margin:14vh auto;padding:26px;background:var(--panel);border:1px solid var(--line);border-radius:10px;box-shadow:var(--shadow)}.login .login-mark{width:42px;height:42px;display:grid;place-items:center;border-radius:9px;background:linear-gradient(145deg,#338dc7,#1b567f);font-weight:800;font-size:12px;margin-bottom:4px}.login h1{font-size:20px}.login button{margin-top:2px}
    @media(max-width:1050px){.sidebar{width:216px;flex-basis:216px}.topbar{padding:0 22px}.workspace{padding:23px 22px 40px}.overview-grid,.section-grid{grid-template-columns:1fr}}
    @media(max-width:760px){.admin-shell{display:block}.sidebar{width:100%;height:auto;position:static;border-right:0;border-bottom:1px solid var(--line)}.brand{height:62px;padding:0 16px}.nav{display:flex;gap:5px;padding:8px 10px;overflow:auto}.nav-group{display:contents}.nav-group-title{display:none}.nav-link{flex:0 0 auto;padding:8px 10px;margin:0}.sidebar-footer{display:none}.topbar{height:auto;min-height:64px;padding:12px 16px;align-items:flex-start}.breadcrumb{display:grid;gap:1px}.top-actions{gap:6px}.refresh-state{display:none}.workspace{padding:18px 14px 32px}.stats{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.stat{padding:13px}.stat b{font-size:23px}.section-head{align-items:flex-start;display:block}.section-meta{display:block;margin-top:7px}.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}.row{flex-wrap:wrap}.row>*{min-width:130px;flex:1}.button-row button{flex:0 0 auto}.panel-head{padding:13px 14px}.body,.panel-body{padding:14px}table{min-width:560px}}
    @media(max-width:430px){.stats{grid-template-columns:1fr 1fr}.stat span{font-size:11px}.eyebrow{display:none}.topbar h1{font-size:17px}.nav-link{font-size:12px}.nav-icon{display:none}}
  </style>
</head>
<body>
  <section id="login" class="panel login stack">
    <div class="login-mark">RC</div><h1>Remote Connect MCP</h1><p class="muted">输入 Center 管理令牌进入控制台。令牌只保存在当前浏览器标签页。</p>
    <input id="token" type="password" autocomplete="current-password" placeholder="管理令牌">
    <button class="primary" id="loginButton">连接 Center</button><div id="loginError" class="error"></div>
  </section>
  <div id="app" class="hidden">
    <div class="admin-shell">
      <aside class="sidebar">
        <a class="brand" href="#overview"><span class="brand-mark">RC</span><span><span class="brand-name">Remote Connect</span><span class="brand-sub">MCP Control Center</span></span></a>
        <nav class="nav" aria-label="主导航">
          <div class="nav-group"><div class="nav-group-title">工作台</div><a class="nav-link active" data-section="overview" href="#overview"><span class="nav-icon">⌂</span>总览</a><a class="nav-link" data-section="create-task" href="#create-task"><span class="nav-icon">＋</span>创建任务</a></div>
          <div class="nav-group"><div class="nav-group-title">资源管理</div><a class="nav-link" data-section="machines" href="#machines"><span class="nav-icon">▦</span>机器列表</a><a class="nav-link" data-section="enrollment" href="#enrollment"><span class="nav-icon">⚿</span>注册令牌</a></div>
          <div class="nav-group"><div class="nav-group-title">运维中心</div><a class="nav-link" data-section="upgrades" href="#upgrades"><span class="nav-icon">↗</span>Agent 升级</a><a class="nav-link" data-section="tokens" href="#tokens"><span class="nav-icon">◇</span>访问令牌</a></div>
          <div class="nav-group"><div class="nav-group-title">执行记录</div><a class="nav-link" data-section="tasks" href="#tasks"><span class="nav-icon">▤</span>任务记录</a><a class="nav-link" data-section="output" href="#output-section"><span class="nav-icon">▣</span>任务输出</a></div>
        </nav>
        <div class="sidebar-footer"><span class="status-dot"></span><span>Center 服务在线</span></div>
      </aside>
      <div class="content">
        <header class="topbar"><div class="breadcrumb"><span class="eyebrow">CONTROL CENTER</span><h1 id="pageTitle">总览</h1></div><div class="top-actions"><span id="refreshState" class="muted refresh-state"></span><button class="icon-button" id="refreshButton" title="立即刷新" aria-label="立即刷新">↻</button><button id="logout">退出</button></div></header>
        <main class="workspace">
          <section id="overview" class="page-section">
            <div class="section-head"><div><h2>运行概览</h2><p>集中查看机器、任务和 Agent 运维状态。</p></div><span class="section-meta">数据每 3 秒自动刷新</span></div>
            <div class="stats"><div class="stat"><b id="machineCount">0</b><span class="stat-label"><i class="mini-dot"></i>已注册机器</span></div><div class="stat"><b id="onlineCount">0</b><span class="stat-label"><i class="mini-dot"></i>在线机器</span></div><div class="stat"><b id="runningCount">0</b><span class="stat-label"><i class="mini-dot"></i>活动任务</span></div><div class="stat"><b id="upgradeCount">0</b><span class="stat-label"><i class="mini-dot"></i>升级活动</span></div></div>
            <div class="overview-grid"><div class="panel"><div class="panel-head"><h3>机器状态</h3><a class="inline-link" href="#machines">查看全部 →</a></div><div class="table-wrap"><table><thead><tr><th>名称</th><th>平台</th><th>状态</th><th>最后心跳</th></tr></thead><tbody id="machines"></tbody></table></div></div><div class="panel"><div class="panel-head"><h3>快捷入口</h3></div><div class="panel-body quick-list"><a class="quick-item" href="#create-task"><span class="quick-icon">＋</span><span><b>创建命令任务</b><span>选择目标机器并执行命令</span></span></a><a class="quick-item" href="#enrollment"><span class="quick-icon">⚿</span><span><b>新增机器</b><span>生成长期或一次性注册令牌</span></span></a><a class="quick-item" href="#upgrades"><span class="quick-icon">↗</span><span><b>升级 Agent</b><span>按 canary 和批次无感发布</span></span></a></div></div></div>
          </section>
          <section id="create-task" class="page-section"><div class="section-head"><div><h2>创建任务</h2><p>向指定 Agent 投递异步命令，长时间运行不会占用连接。</p></div></div><div class="section-grid"><div class="panel"><div class="panel-head"><h3>命令配置</h3><span class="muted">Shell / PowerShell</span></div><div class="panel-body stack"><div class="form-grid"><div class="field"><label for="machine">目标机器</label><select id="machine"></select></div><div class="field"><label for="timeout">超时秒数</label><input id="timeout" type="number" min="0" value="0" title="0 表示不限制运行时间"><small>0 表示不限制运行时间</small></div><div class="field full"><label for="cwd">工作目录</label><input id="cwd" placeholder="留空使用 Agent 默认目录"></div><div class="field full"><label for="command">执行命令</label><textarea id="command" spellcheck="false" placeholder="输入 Shell 命令"></textarea></div></div><div class="button-row"><div id="runError" class="error"></div><button class="primary" id="run">开始执行</button></div></div></div><div class="help-box"><strong>任务执行说明</strong>Center 会先创建持久化任务，再由在线 Agent 拉取执行。命令输出会分段保存，可在“任务输出”中持续读取；连接中断时任务仍会继续运行。</div></div></section>
          <section id="machines" class="page-section"><div class="section-head"><div><h2>机器列表</h2><p>所有已注册 Agent 的在线状态和最近心跳。</p></div></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>名称</th><th>平台</th><th>状态</th><th>最后心跳</th></tr></thead><tbody id="machineList"></tbody></table></div></div></section>
          <section id="upgrades" class="page-section"><div class="section-head"><div><h2>Agent 无感升级</h2><p>按 canary 和批次推进在线机器升级，失败会自动暂停。</p></div></div><div class="panel"><div class="panel-body stack"><div class="form-grid"><div class="field"><label for="upgradeVersion">Release 版本</label><input id="upgradeVersion" placeholder="例如 v1.3.1"></div><div class="field"><label for="canaryCount">首批 canary 数量</label><input id="canaryCount" type="number" min="1" value="1"></div><div class="field"><label for="batchSize">后续每批数量</label><input id="batchSize" type="number" min="1" value="3"></div><div class="field"><label>&nbsp;</label><button class="primary" id="startUpgrade">升级全部在线机器</button></div></div><div class="muted">Center 自动解析 GitHub Release 的跨平台 Agent 和 SHA-256；canary 成功后自动推进批次。</div><div id="upgradeError" class="error"></div><div class="table-wrap"><table><thead><tr><th>活动</th><th>版本</th><th>状态</th><th>进度</th><th>批次</th><th>操作</th></tr></thead><tbody id="upgrades"></tbody></table></div></div></div></section>
          <section id="enrollment" class="page-section"><div class="section-head"><div><h2>新增机器注册令牌</h2><p>为每台机器生成独立注册凭据，长期令牌默认与机器名绑定。</p></div></div><div class="panel"><div class="panel-body stack"><div class="form-grid"><div class="field"><label for="enrollmentName">机器名称</label><input id="enrollmentName" placeholder="例如 oraclecloud-hs-new"></div><div class="field"><label for="enrollmentPlatform">目标平台</label><select id="enrollmentPlatform"><option value="linux">Linux</option><option value="windows">Windows</option></select></div><div class="field"><label for="enrollmentLifetime">令牌有效期</label><select id="enrollmentLifetime"><option value="0" selected>长期 · 单机专用</option><option value="3600">一次性 · 1 小时</option><option value="86400">一次性 · 24 小时</option><option value="604800">一次性 · 7 天</option><option value="2592000">一次性 · 30 天</option></select></div><div class="field"><label>&nbsp;</label><button class="primary" id="createEnrollment">生成机器 Token</button></div></div><div class="row"><input id="enrollmentToken" type="password" readonly placeholder="生成后仅在这里显示一次"><button id="copyEnrollmentToken">复制 Token</button><button id="copyEnrollmentConfig">复制配置</button></div><pre id="enrollmentConfig" class="code-box">先生成注册 Token。目标 Agent 注册成功后会获得每机独立身份。</pre><div class="muted">长期 Token 与一个机器名称永久绑定，可用于该机器安装、重装和身份恢复，手工撤销前不会过期；一次性 Token 成功注册后失效。明文只显示一次，Center 只保存 SHA-256 摘要。</div><div id="enrollmentNotice" class="muted"></div><div id="enrollmentError" class="error"></div><div class="table-wrap"><table><thead><tr><th>机器</th><th>类型</th><th>状态</th><th>使用</th><th>过期时间</th><th>操作</th></tr></thead><tbody id="enrollmentTokens"></tbody></table></div></div></div></section>
          <section id="tokens" class="page-section"><div class="section-head"><div><h2>访问令牌轮换</h2><p>轮换 MCP、控制台或共享 Enrollment 令牌，并配置旧令牌宽限期。</p></div></div><div class="panel"><div class="panel-body stack"><div class="form-grid"><div class="field"><label for="tokenKind">令牌类型</label><select id="tokenKind"><option value="mcp">MCP · ChatGPT</option><option value="admin">Admin · 控制台</option><option value="enrollment">Enrollment · Agent 注册</option></select></div><div class="field"><label for="tokenGrace">旧令牌宽限秒数</label><input id="tokenGrace" type="number" min="0" max="86400" value="300" title="旧令牌宽限秒数"></div><div class="field"><label>&nbsp;</label><button id="generateToken">本地生成新令牌</button></div></div><div class="row"><input id="newToken" type="password" autocomplete="new-password" placeholder="新令牌，至少 32 个字符"><input id="confirmToken" type="password" autocomplete="new-password" placeholder="再次输入新令牌"><button id="copyToken">复制</button><button class="danger" id="rotateToken">确认轮换</button></div><div class="muted">Center 只持久化令牌 SHA-256 摘要。K8S Secret/env 变化可作为恢复入口；正常重启不会覆盖控制台轮换结果。</div><div id="tokenNotice" class="muted"></div><div id="tokenError" class="error"></div><div class="table-wrap"><table><thead><tr><th>类型</th><th>来源</th><th>更新时间</th><th>旧令牌有效至</th></tr></thead><tbody id="accessTokens"></tbody></table></div></div></div></section>
          <section id="tasks" class="page-section"><div class="section-head"><div><h2>任务记录</h2><p>查看最近任务、目标机器、执行状态和命令摘要。</p></div></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>任务</th><th>机器</th><th>状态</th><th>命令</th><th>创建时间</th></tr></thead><tbody id="tasksTable"></tbody></table></div></div></section>
          <section id="output-section" class="page-section"><div class="section-head"><div><h2>任务输出</h2><p>按任务读取持久化输出，可取消仍在运行的任务。</p></div></div><div class="panel"><div class="panel-body stack"><div class="row"><span id="selectedTask" class="muted">选择一个任务</span><button id="cancel" class="danger" disabled>取消任务</button><button id="reloadOutput" disabled>刷新输出</button></div><pre id="output"></pre></div></div></section>
        </main>
      </div>
    </div>
  </div>
  <script>
    const $=id=>document.getElementById(id);let token=sessionStorage.getItem('remoteConnectMcpAdminToken')||'';let machines=[],tasks=[],upgrades=[],accessTokens=[],enrollmentTokens=[],selected='',latestEnrollment={name:'',token:''};
    const pageTitles={overview:'总览','create-task':'创建任务',machines:'机器列表',upgrades:'Agent 升级',enrollment:'注册令牌',tokens:'访问令牌',tasks:'任务记录','output-section':'任务输出'};
    function syncNavigation(){let current=location.hash.slice(1)||'overview';if(!pageTitles[current])current='overview';document.querySelectorAll('.nav-link').forEach(link=>link.classList.toggle('active',link.dataset.section===current));document.querySelectorAll('.page-section').forEach(section=>section.classList.toggle('active-section',section.id===current));$('pageTitle').textContent=pageTitles[current]||'总览'}
    async function api(path,options={}){const headers={...(options.headers||{}),Authorization:'Bearer '+token};if(options.body)headers['Content-Type']='application/json';const response=await fetch('/api/v1/'+path,{...options,headers});const body=await response.json().catch(()=>({error:'响应不是 JSON'}));if(!response.ok)throw new Error(body.error||('HTTP '+response.status));return body}
    function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    function date(value){if(!value)return '—';return new Date(value).toLocaleString()}
    async function login(){token=$('token').value.trim();try{await api('machines');sessionStorage.setItem('remoteConnectMcpAdminToken',token);$('login').classList.add('hidden');$('app').classList.remove('hidden');$('loginError').textContent='';syncNavigation();await refresh()}catch(error){$('loginError').textContent=error.message}}
    async function refresh(){try{const [machineData,taskData,upgradeData,tokenData,enrollmentData]=await Promise.all([api('machines'),api('tasks?limit=100'),api('upgrades?limit=20'),api('tokens'),api('enrollment-tokens?limit=100')]);machines=machineData.machines||[];tasks=taskData.tasks||[];upgrades=upgradeData.upgrades||[];accessTokens=tokenData.tokens||[];enrollmentTokens=enrollmentData.enrollment_tokens||[];render();$('refreshState').textContent='已刷新 '+new Date().toLocaleTimeString()}catch(error){$('refreshState').textContent='刷新失败：'+error.message}}
    function render(){const names=Object.fromEntries(machines.map(m=>[m.id,m.name]));$('machineCount').textContent=machines.length;$('onlineCount').textContent=machines.filter(m=>m.online).length;$('runningCount').textContent=tasks.filter(t=>['queued','dispatching','running','cancel_requested'].includes(t.status)).length;$('upgradeCount').textContent=upgrades.filter(u=>['running','paused'].includes(u.status)).length;
      const chosen=$('machine').value;$('machine').innerHTML=machines.map(m=>'<option value="'+esc(m.id)+'">'+esc(m.name)+(m.online?' · 在线':' · 离线')+'</option>').join('');if(chosen)$('machine').value=chosen;
      const machineRows=machines.map(m=>'<tr><td><b>'+esc(m.name)+'</b><br><span class="muted">'+esc(m.id)+'</span></td><td>'+esc(m.os)+' / '+esc(m.arch)+'</td><td><span class="pill '+(m.online?'online':'offline')+'">'+(m.online?'在线':'离线')+'</span></td><td>'+date(m.last_seen)+'</td></tr>').join('');$('machines').innerHTML=machineRows;$('machineList').innerHTML=machineRows;
      $('upgrades').innerHTML=upgrades.map(u=>{const done=(u.targets||[]).filter(t=>t.status==='completed').length,failed=(u.targets||[]).filter(t=>t.status==='failed').length,total=(u.targets||[]).length;const actions=u.status==='paused'?'<button data-upgrade="'+esc(u.id)+'" data-action="resume">重试并继续</button>':(u.status==='running'?'<button class="danger" data-upgrade="'+esc(u.id)+'" data-action="cancel">取消</button>':'');return '<tr><td>'+esc(u.id)+'</td><td><b>'+esc(u.version)+'</b></td><td><span class="pill '+esc(u.status)+'">'+esc(u.status)+'</span></td><td>'+done+' / '+total+(failed?' · 失败 '+failed:'')+'</td><td>canary '+esc(u.canary_count)+' · 每批 '+esc(u.batch_size)+'</td><td>'+actions+'</td></tr>'}).join('');document.querySelectorAll('[data-upgrade]').forEach(button=>button.onclick=()=>upgradeAction(button.dataset.upgrade,button.dataset.action));
      $('enrollmentTokens').innerHTML=enrollmentTokens.map(t=>'<tr><td><b>'+esc(t.name)+'</b><br><span class="muted">'+esc(t.id)+'</span></td><td>'+esc(t.persistent?'长期单机':'一次性')+'</td><td><span class="pill '+esc(t.status)+'">'+esc(t.status)+'</span></td><td>'+esc(t.uses)+(t.max_uses?' / '+esc(t.max_uses):'')+'</td><td>'+(t.persistent?'长期':date(t.expires_at))+'</td><td>'+(t.status==='active'?'<button class="danger" data-enrollment="'+esc(t.id)+'">撤销</button>':'—')+'</td></tr>').join('');document.querySelectorAll('[data-enrollment]').forEach(button=>button.onclick=()=>revokeEnrollment(button.dataset.enrollment));
      $('accessTokens').innerHTML=accessTokens.map(t=>'<tr><td><b>'+esc(t.kind)+'</b></td><td>'+esc(t.source==='environment'?'K8S env 恢复/初始值':'Center 控制台')+'</td><td>'+date(t.updated_at)+'</td><td>'+date(t.previous_valid_until)+'</td></tr>').join('');
      const taskRows=tasks.map(t=>'<tr data-task="'+esc(t.id)+'"><td>'+esc(t.id)+'</td><td>'+esc(names[t.machine_id]||t.machine_id)+'</td><td><span class="pill '+esc(t.status)+'">'+esc(t.status)+'</span></td><td><code>'+esc(t.command).slice(0,160)+'</code></td><td>'+date(t.created_at)+'</td></tr>').join('');$('tasksTable').innerHTML=taskRows;document.querySelectorAll('[data-task]').forEach(row=>row.onclick=()=>{selectTask(row.dataset.task);location.hash='output-section'});}
    async function run(){const payload={machine_id:$('machine').value,command:$('command').value,cwd:$('cwd').value,timeout_seconds:Number($('timeout').value||0)};$('runError').textContent='';try{const task=await api('tasks',{method:'POST',body:JSON.stringify(payload)});selected=task.id;$('selectedTask').textContent=selected;$('cancel').disabled=false;$('reloadOutput').disabled=false;await refresh();await loadOutput()}catch(error){$('runError').textContent=error.message}}
    async function selectTask(id){selected=id;$('selectedTask').textContent=id;$('cancel').disabled=false;$('reloadOutput').disabled=false;await loadOutput()}
    async function loadOutput(){if(!selected)return;try{const result=await api('tasks/'+encodeURIComponent(selected)+'/output?cursor=0&limit=1048576');$('output').textContent=result.text||'';$('output').scrollTop=$('output').scrollHeight}catch(error){$('output').textContent='读取失败：'+error.message}}
    async function cancel(){if(!selected)return;await api('tasks/'+encodeURIComponent(selected)+'/cancel',{method:'POST'});await refresh()}
    async function startUpgrade(){const payload={version:$('upgradeVersion').value.trim(),canary_count:Number($('canaryCount').value||1),batch_size:Number($('batchSize').value||3)};$('upgradeError').textContent='';try{await api('upgrades',{method:'POST',body:JSON.stringify(payload)});await refresh()}catch(error){$('upgradeError').textContent=error.message}}
    async function upgradeAction(id,action){$('upgradeError').textContent='';try{await api('upgrades/'+encodeURIComponent(id)+'/'+action,{method:'POST'});await refresh()}catch(error){$('upgradeError').textContent=error.message}}
    function renderEnrollmentConfig(){if(!latestEnrollment.token)return;const url='https://agent.example.invalid',name=latestEnrollment.name,value=latestEnrollment.token;if($('enrollmentPlatform').value==='windows'){$('enrollmentConfig').textContent=".\\scripts\\install-agent.ps1 -BinaryPath .\\remote-connect-mcp-agent.exe -CenterUrl '"+url+"' -EnrollmentToken '"+value+"' -AgentName '"+name+"' -DefaultCwd 'C:\\'"}else{$('enrollmentConfig').textContent="sudo env REMOTE_CONNECT_MCP_AGENT_CENTER_URL='"+url+"' REMOTE_CONNECT_MCP_AGENT_ENROLLMENT_TOKEN='"+value+"' REMOTE_CONNECT_MCP_AGENT_NAME='"+name+"' ./scripts/install-agent.sh"}}
    async function createEnrollment(){const name=$('enrollmentName').value.trim(),expires=Number($('enrollmentLifetime').value),persistent=expires===0;$('enrollmentError').textContent='';$('enrollmentNotice').textContent='';if(!name){$('enrollmentError').textContent='请输入目标机器名称。';return}try{const result=await api('enrollment-tokens',{method:'POST',body:JSON.stringify({name,expires_seconds:expires,max_uses:persistent?0:1,persistent})});latestEnrollment={name,token:result.token};$('enrollmentToken').value=result.token;renderEnrollmentConfig();$('enrollmentNotice').textContent=persistent?'已生成该机器的长期 Token。明文不会再次显示，请保存到对应机器。':'已生成一次性 Token。明文不会再次显示，请立即复制到目标机器。';await refresh()}catch(error){$('enrollmentError').textContent=error.message}}
    async function copyEnrollmentToken(){const value=$('enrollmentToken').value;if(!value)return;try{await navigator.clipboard.writeText(value);$('enrollmentNotice').textContent='注册 Token 已复制。'}catch(error){$('enrollmentError').textContent='复制失败：'+error.message}}
    async function copyEnrollmentConfig(){const value=$('enrollmentConfig').textContent;if(!$('enrollmentToken').value)return;try{await navigator.clipboard.writeText(value);$('enrollmentNotice').textContent='Agent 配置已复制。'}catch(error){$('enrollmentError').textContent='复制失败：'+error.message}}
    async function revokeEnrollment(id){$('enrollmentError').textContent='';if(!confirm('确认撤销这个注册 Token？'))return;try{await api('enrollment-tokens/'+encodeURIComponent(id)+'/revoke',{method:'POST'});await refresh()}catch(error){$('enrollmentError').textContent=error.message}}
    function generateToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);const value=btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');$('newToken').value=value;$('confirmToken').value=value;$('tokenNotice').textContent='已在浏览器本地生成新令牌；请保存后再轮换。'}
    async function copyToken(){const value=$('newToken').value;if(!value)return;try{await navigator.clipboard.writeText(value);$('tokenNotice').textContent='新令牌已复制到剪贴板。'}catch(error){$('tokenError').textContent='复制失败：'+error.message}}
    async function rotateAccessToken(){const kind=$('tokenKind').value,newValue=$('newToken').value.trim(),confirmed=$('confirmToken').value.trim(),grace=Number($('tokenGrace').value||0);$('tokenError').textContent='';$('tokenNotice').textContent='';if(newValue.length<32){$('tokenError').textContent='新令牌至少需要 32 个字符。';return}if(newValue!==confirmed){$('tokenError').textContent='两次输入的新令牌不一致。';return}if(!Number.isInteger(grace)||grace<0||grace>86400){$('tokenError').textContent='宽限期必须是 0 到 86400 秒。';return}if(!confirm('确认轮换 '+kind+' 令牌？'))return;try{await api('tokens/'+kind+'/rotate',{method:'POST',body:JSON.stringify({new_token:newValue,grace_seconds:grace})});if(kind==='admin'){token=newValue;sessionStorage.setItem('remoteConnectMcpAdminToken',token);$('newToken').value='';$('confirmToken').value=''}$('tokenNotice').textContent=kind==='mcp'?'MCP 令牌已轮换；请在宽限期内更新 ChatGPT Web 连接器。':(kind==='admin'?'Admin 令牌已轮换，当前页面已切换到新令牌。':'Enrollment 令牌已轮换；已注册 Agent 身份不受影响。');await refresh()}catch(error){$('tokenError').textContent=error.message}}
    $('loginButton').onclick=login;$('token').onkeydown=e=>{if(e.key==='Enter')login()};$('run').onclick=run;$('cancel').onclick=cancel;$('reloadOutput').onclick=loadOutput;$('startUpgrade').onclick=startUpgrade;$('createEnrollment').onclick=createEnrollment;$('copyEnrollmentToken').onclick=copyEnrollmentToken;$('copyEnrollmentConfig').onclick=copyEnrollmentConfig;$('enrollmentPlatform').onchange=renderEnrollmentConfig;$('generateToken').onclick=generateToken;$('copyToken').onclick=copyToken;$('rotateToken').onclick=rotateAccessToken;$('refreshButton').onclick=refresh;$('logout').onclick=()=>{sessionStorage.removeItem('remoteConnectMcpAdminToken');location.reload()};window.addEventListener('hashchange',syncNavigation);syncNavigation();
    if(token){$('token').value=token;login()}setInterval(()=>{if(!$('app').classList.contains('hidden')){refresh();if(selected)loadOutput()}},3000);
  </script>
</body>
</html>`
