apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - routes.yaml
images:
  - name: docker.io/speedproxy/remote-connect-mcp-center
    newName: docker.io/speedproxy/remote-connect-mcp-center
    newTag: latest
